spring:
  application:
    name: pwandora

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  profiles:
    group:
      local:
        - local
      prod:
        - prod
    include:
      - key

  servlet:
    multipart:
      max-file-size: 2000MB # 파일 최대 사이즈
      max-request-size: 2000MB # 요청 당 최대 사이즈

  datasource:
    hikari:
      minimum-idle: 10  # 최소 유지할 유휴 커넥션 (적절히 설정)
      maximum-pool-size: 40  # 최대 커넥션 개수 (CPU 코어 * 10 권장)
      idle-timeout: 30000  # 유휴 상태에서 제거되는 시간 (30초)
      max-lifetime: 1800000  # 최대 커넥션 수명 (30분, DB 설정보다 낮게)
      connection-timeout: 3000  # 커넥션 대기 최대 시간 (3초)


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

cloud:
  aws:
    credentials:
      access-key: ENC(V3MTwJ+e2sn22WoSM2P5PnFOAgf825oreL1/rBSR17Y=)
      secret-key: ENC(55eyZ6HMmT86/vnWI8a0nvIPIvTzIIYM7czj/sxQISL4b+zZmeMJ9iOmhZ4T0wg7f+xU9P/lxbc=)
    region:
      static: ap-northeast-2
    s3:
      bucket: pwandora-storage
