import king from '@/assets/images/apps/K-ing.png'
import ddangx3 from '@/assets/images/apps/Ddangx3.png'
import starbucks from '@/assets/images/apps/Starbucks.png'
import x from '@/assets/images/apps/X.png'
import reddit from '@/assets/images/apps/Reddit.png'
import youtube from '@/assets/images/apps/Youtube.png'
import facebook from '@/assets/images/apps/Facebook.png'
import spotify from '@/assets/images/apps/Spotify.png'
import tiktok from '@/assets/images/apps/TikTok.png'
import instagram from '@/assets/images/apps/Instagram.png'

import screenshots1 from '@/assets/images/screenshots/instagram1.webp'
import screenshots2 from '@/assets/images/screenshots/instagram2.webp'
import screenshots3 from '@/assets/images/screenshots/instagram3.webp'
import screenshots4 from '@/assets/images/screenshots/instagram4.webp'
import screenshots5 from '@/assets/images/screenshots/instagram5.webp'
import screenshots6 from '@/assets/images/screenshots/instagram6.webp'
import screenshots7 from '@/assets/images/screenshots/instagram7.webp'

export const appDetails = [
  {
    id: 1,
    name: 'K-ing',
    icon: king,
    category: 'Food & Drink',
    installed: false,
    downloads: 1213,
    size: '1.5MB',
    description: 'Order food and drinks from K-ing',
    ageRating: '3+',
    languages: 'English, Korean',
    permissions: 'Location, Storage',
    screenshots: [
      screenshots1,
      screenshots2,
      screenshots3,
      screenshots4,
      screenshots5,
      screenshots6,
      screenshots7,
    ],
  },
  {
    id: 2,
    name: 'Ddangx3',
    icon: ddangx3,
    category: 'Shopping',
    installed: false,
    downloads: 64123,
    size: '5.2MB',
    description:
      'An online auction platform for buying and selling second-hand items.',
    ageRating: '7+',
    languages: 'English, Japanese, Korean',
    permissions: 'Storage, Contacts',
    screenshots: [
      screenshots1,
      screenshots2,
      screenshots3,
      screenshots4,
      screenshots5,
      screenshots6,
      screenshots7,
    ],
  },
  {
    id: 3,
    name: 'Starbucks',
    icon: starbucks,
    category: 'Food & Drink',
    installed: true,
    downloads: 12641213,
    size: '1.3MB',
    description: 'Order your favorite Starbucks drinks',
    ageRating: '3+',
    languages: 'English, Spanish',
    permissions: 'Location, Storage',
    screenshots: [
      screenshots1,
      screenshots2,
      screenshots3,
      screenshots4,
      screenshots5,
      screenshots6,
      screenshots7,
    ],
  },
  {
    id: 4,
    name: 'X',
    icon: x,
    category: 'Social Media',
    installed: false,
    downloads: 4841213,
    size: '2.1MB',
    description: 'Connect with friends on X',
    ageRating: '12+',
    languages: 'English, Chinese',
    permissions: 'Location, Camera, Microphone, Storage, Contacts',
    screenshots: [
      screenshots1,
      screenshots2,
      screenshots3,
      screenshots4,
      screenshots5,
      screenshots6,
      screenshots7,
    ],
  },
  {
    id: 5,
    name: 'Reddit',
    icon: reddit,
    category: 'Social Media',
    installed: true,
    downloads: 341213,
    size: '3.4MB',
    description: 'Join communities on Reddit',
    ageRating: '17+',
    languages: 'English',
    permissions: 'Location, Storage',
    screenshots: [
      screenshots1,
      screenshots2,
      screenshots3,
      screenshots4,
      screenshots5,
      screenshots6,
      screenshots7,
    ],
  },
  {
    id: 6,
    name: 'Youtube',
    icon: youtube,
    category: 'Video',
    installed: false,
    downloads: 965841213,
    size: '4.7MB',
    description: 'Watch videos on Youtube',
    ageRating: '12+',
    languages: 'English, Spanish, French',
    permissions: 'Location, Camera, Microphone, Storage',
    screenshots: [
      screenshots1,
      screenshots2,
      screenshots3,
      screenshots4,
      screenshots5,
      screenshots6,
      screenshots7,
    ],
  },
  {
    id: 7,
    name: 'Facebook',
    icon: facebook,
    category: 'Social Media',
    installed: true,
    downloads: 6841213,
    size: '3.6MB',
    description: 'Connect with friends on Facebook',
    ageRating: '12+',
    languages: 'English, Spanish, French, German',
    permissions: 'Location, Camera, Microphone, Storage, Contacts',
    screenshots: [
      screenshots1,
      screenshots2,
      screenshots3,
      screenshots4,
      screenshots5,
      screenshots6,
      screenshots7,
    ],
  },
  {
    id: 8,
    name: 'Spotify',
    icon: spotify,
    category: 'Music',
    installed: true,
    downloads: 2841213,
    size: '2.8MB',
    description: 'Listen to music on Spotify',
    ageRating: '12+',
    languages: 'English, Spanish, French, German, Japanese',
    permissions: 'Location, Storage, Contacts',
    screenshots: [
      screenshots1,
      screenshots2,
      screenshots3,
      screenshots4,
      screenshots5,
      screenshots6,
      screenshots7,
    ],
  },
  {
    id: 9,
    name: 'TikTok',
    icon: tiktok,
    category: 'Video',
    installed: true,
    downloads: 551213,
    size: '4.3MB',
    description: 'Create and watch short videos on TikTok',
    ageRating: '12+',
    languages: 'English, Spanish, French, German, Japanese, Korean',
    permissions: 'Location, Camera, Microphone, Storage, Contacts',
    screenshots: [
      screenshots1,
      screenshots2,
      screenshots3,
      screenshots4,
      screenshots5,
      screenshots6,
      screenshots7,
    ],
  },
  {
    id: 10,
    name: 'Instagram',
    icon: instagram,
    category: 'Social Media',
    installed: false,
    downloads: 12841213,
    size: '4.12MB',
    description:
      'Create & share photos, stories, & reels with friends you love',
    ageRating: '12+',
    languages: 'English, Arabic, French, German, Indonesian',
    permissions: 'Location, Camera, Microphone, Storage, Contacts',
    screenshots: [
      screenshots1,
      screenshots2,
      screenshots3,
      screenshots4,
      screenshots5,
      screenshots6,
      screenshots7,
    ],
  },
] as const
